FROM golang:1.26-alpine AS dev

RUN apk add --no-cache ca-certificates

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/bin/api ./cmd

EXPOSE 8080

CMD ["/app/bin/api"]
