// Package apitest builds the DTOs the HTTP tests need. DTO fields are
// unexported, so a test cannot write a DTO literal: these factories build a
// domain entity and call the real mapper.
//
// See docs/development/testing.md#http-tests.
package apitest

import (
	"testing"
	"time"

	"github.com/rafaelblt/go-auth/internal/domain/session"
	"github.com/rafaelblt/go-auth/internal/domain/user"
	"github.com/rafaelblt/go-auth/internal/port"
	"github.com/rafaelblt/go-auth/internal/testutil/sessiontest"
	"github.com/rafaelblt/go-auth/internal/testutil/usertest"
	"github.com/rafaelblt/go-auth/internal/usecase"
)

// NewUserDTO maps a default user, adjusted by override, the same way a use
// case does.
func NewUserDTO(t *testing.T, override func(p *user.RestoreParams)) usecase.UserDTO {
	t.Helper()
	return usecase.MapUserToDTO(usertest.NewUser(t, override))
}

func NewAccessTokenDTO(t *testing.T) usecase.AccessTokenDTO {
	t.Helper()

	issued := port.AccessTokenIssued{
		Token:     sessiontest.MustAccessToken(t, "[generated by apitest.NewAccessTokenDTO]"),
		IssuedAt:  time.Date(2031, 3, 14, 14, 39, 26, 0, time.UTC),
		ExpiresAt: time.Date(2031, 3, 14, 15, 9, 26, 0, time.UTC),
	}
	return usecase.MapAccessTokenIssuedToDTO(issued)
}

// NewRefreshTokenDTO maps a default refresh token, adjusted by override, the
// same way a use case does.
func NewRefreshTokenDTO(t *testing.T, override func(p *session.RefreshTokenRestoreParams)) usecase.RefreshTokenDTO {
	t.Helper()

	token := sessiontest.NewRefreshToken(t, override)
	secret := sessiontest.NewRefreshTokenSecret(t)
	return usecase.MapRefreshTokenToDTO(token, secret)
}
