package apitest

import (
	"testing"
	"time"

	"github.com/rafaelblt/go-auth/internal/domain/user"
	"github.com/rafaelblt/go-auth/internal/port"
	"github.com/rafaelblt/go-auth/internal/testutil/sessiontest"
	"github.com/rafaelblt/go-auth/internal/testutil/usertest"
	"github.com/rafaelblt/go-auth/internal/usecase"
)

// NewUserDTO maps a default user, adjusted by override, the same way a use
// case does.
func NewUserDTO(t *testing.T, override func(p *user.RestoreParams)) usecase.UserDTO {
	t.Helper()
	return usecase.MapUserToDTO(usertest.NewUser(t, override))
}

func NewAccessTokenDTO(t *testing.T) usecase.AccessTokenDTO {
	t.Helper()

	issued := port.AccessTokenIssued{
		Token:     sessiontest.MustAccessToken(t, "[generated by apitest.NewAccessTokenDTO]"),
		ExpiresAt: time.Date(2031, 3, 14, 15, 9, 26, 0, time.UTC),
	}
	return usecase.MapAccessTokenIssuedToDTO(issued)
}

func NewRefreshTokenDTO(t *testing.T) usecase.RefreshTokenDTO {
	t.Helper()

	token := sessiontest.NewRefreshToken(t, nil)
	secret := sessiontest.NewRefreshTokenSecret(t)
	return usecase.MapRefreshTokenToDTO(token, secret)
}
