package apitest

import (
	"context"
	"time"

	"github.com/rafaelblt/go-auth/internal/usecase"
	"github.com/rafaelblt/go-auth/internal/usecase/login"
)

type FakeLogin struct {
	inputs []login.Input
	err    error
}

func NewFakeLogin() *FakeLogin {
	fr := FakeLogin{
		inputs: make([]login.Input, 0),
		err:    nil,
	}
	return &fr
}

func (fl *FakeLogin) Execute(ctx context.Context, in login.Input) (login.Output, error) {
	fl.inputs = append(fl.inputs, in)

	if fl.err != nil {
		return login.Output{}, fl.err
	}

	return fl.DefaultOutput(), nil
}

func (fl *FakeLogin) DefaultOutput() login.Output {
	accessDTO := usecase.AccessTokenDTO{
		Value: "[generated by apitest.FakeLogin]",
		ExpiresAt: time.Now().Add(time.Hour),
	}
	refreshDTO := usecase.RefreshTokenDTO{
		Value: "[generated by apitest.FakeLogin]",
		ExpiresAt: time.Now().Add(time.Hour),
	}

	out := login.Output{
		AccessToken: accessDTO,
		RefreshToken: refreshDTO,
	}
	return out
}

func (fl *FakeLogin) SetError(err error) {
	fl.err = err
}
