package apitest

import (
	"context"
	"time"

	"github.com/rafaelblt/go-auth/internal/usecase"
	"github.com/rafaelblt/go-auth/internal/usecase/register"
	"github.com/rafaelblt/go-auth/internal/user"
)

type FakeRegister struct {
	inputs []register.Input
	err    error
}

func NewFakeRegister() *FakeRegister {
	fr := FakeRegister{
		inputs: make([]register.Input, 0),
		err:    nil,
	}
	return &fr
}

func (fr *FakeRegister) Execute(ctx context.Context, in register.Input) (register.Output, error) {
	fr.inputs = append(fr.inputs, in)

	if fr.err != nil {
		return register.Output{}, fr.err
	}

	dto := usecase.UserDTO{
		ID:        "[generated by apitest.FakeRegister]",
		Username:  in.Username,
		Status:    user.StatusActive.String(),
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}

	out := register.Output{User: dto}
	return out, nil
}

func (fr *FakeRegister) SetError(err error) {
	fr.err = err
}
