package apitest

import (
	"context"
	"time"

	"github.com/rafaelblt/go-auth/internal/usecase"
	"github.com/rafaelblt/go-auth/internal/usecase/refresh"
)

type FakeRefresh struct {
	inputs  []refresh.Input
	outputs []refresh.Output
	err     error
}

func NewFakeRefresh() *FakeRefresh {
	fr := FakeRefresh{
		inputs: make([]refresh.Input, 0),
		err:    nil,
	}
	return &fr
}

func (r *FakeRefresh) Execute(ctx context.Context, in refresh.Input) (refresh.Output, error) {
	r.inputs = append(r.inputs, in)

	if r.err != nil {
		return refresh.Output{}, r.err
	}

	out := r.DefaultOutput()
	r.outputs = append(r.outputs, out)
	return out, nil
}

func (r *FakeRefresh) DefaultOutput() refresh.Output {
	accessDTO := usecase.AccessTokenDTO{
		Value:     "[generated by apitest.FakeRefresh]",
		ExpiresAt: time.Now().Add(time.Hour),
	}
	refreshDTO := usecase.RefreshTokenDTO{
		Value:     "[generated by apitest.FakeRefresh]",
		ExpiresAt: time.Now().Add(time.Hour),
	}

	out := refresh.Output{
		AccessToken:  accessDTO,
		RefreshToken: refreshDTO,
	}
	return out
}

func (r *FakeRefresh) Inputs() []refresh.Input {
	return r.inputs
}

func (r *FakeRefresh) Outputs() []refresh.Output {
	return r.outputs
}

func (r *FakeRefresh) SetError(err error) {
	r.err = err
}
